# Altyapı (from dockerHub):    #hubDocker üzerinden bulduğum sürümün ismini yazdım
FROM node:20.9.0-alpine      

# Çalışma Alanı:
WORKDIR /app

# Dosyaları Aktar: COPY local inImage
# COPY hello.js /app            #(nokta nokta kullanmanın esprisi kısalığının yanında bulunduğum yerdeki tüm dosyaları kopyala)
COPY . .                        

# After build (when image to container):
# docker run imagename
CMD node hello.js
